compile:
	clear
	gcc loadPreorder.c writePostorder.c pa2.c tree.h -g -o a.out

test3:
	make compile
	./a.out "/home/mo/ece368/hw2/pa2_examples/examples/3.pr" "/home/mo/ece368/hw2/outputs/3.po"

test8:
	make compile
	./a.out "/home/mo/ece368/hw2/pa2_examples/examples/8.pr" "/home/mo/ece368/hw2/outputs/8.po"


